# Generated by Django 3.1.7 on 2021-04-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=100)),
                ('end_date', models.DateField()),
                ('body', models.TextField()),
                ('updated', models.DateField(auto_now=True)),
                ('finished', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('finished', models.BooleanField()),
            ],
        ),
    ]
