# Generated by Django 3.1.7 on 2021-04-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner_todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('finished',)},
        ),
        migrations.RemoveField(
            model_name='todo',
            name='created',
        ),
    ]
